package com.btk.spm.data.db;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import org.junit.BeforeClass;
import org.junit.Test;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Reads the committed schema, {@code app/schemas/com.btk.spm.data.db.AppDatabase/1.json}, on the JVM
 * and checks it says what the data model is meant to be (Issue 12).
 *
 * <p>The report's ER diagram (Issue 34) is drawn from this file, so the file itself is under test: the
 * three tables with their columns, SQLite types and nullability, the foreign key from
 * {@code recipe_ingredients} to {@code recipes} with {@code ON DELETE CASCADE}, and the index on
 * {@code recipe_id}. The gate's {@code schema} stage keeps the file equal to what Room generates; this
 * test keeps what Room generates equal to the design.
 */
public class SchemaFileTest {

    /** The committed schema, relative to the module directory Gradle runs unit tests from. */
    private static final Path SCHEMA =
            Paths.get("schemas", "com.btk.spm.data.db.AppDatabase", "1.json");

    private static JSONObject database;

    @BeforeClass
    public static void readTheCommittedSchema() throws IOException, JSONException {
        assertTrue("No schema at " + SCHEMA.toAbsolutePath(), Files.isRegularFile(SCHEMA));
        String json = new String(Files.readAllBytes(SCHEMA), StandardCharsets.UTF_8);
        database = new JSONObject(json).getJSONObject("database");
    }

    @Test
    public void isVersionOne() throws JSONException {
        assertEquals(1, database.getInt("version"));
        assertFalse(database.getString("identityHash").isEmpty());
    }

    @Test
    public void holdsExactlyTheThreeTables() throws JSONException {
        JSONArray entities = database.getJSONArray("entities");
        List<String> tables = new ArrayList<>();
        for (int i = 0; i < entities.length(); i++) {
            tables.add(entities.getJSONObject(i).getString("tableName"));
        }
        assertEquals(Arrays.asList("pantry_items", "recipes", "recipe_ingredients"), tables);
    }

    @Test
    public void pantryItemsHasItsColumns() throws JSONException {
        // name -> "TYPE NOT NULL" or "TYPE NULL"; expiry_date is nullable: null means never expires (decision 6)
        assertColumns("pantry_items", columns(
                "id", "INTEGER NOT NULL",
                "name", "TEXT NOT NULL",
                "quantity", "REAL NOT NULL",
                "unit", "TEXT NOT NULL",
                "expiry_date", "INTEGER NULL",
                "created_at", "INTEGER NOT NULL"));
        assertAutoGeneratedKey("pantry_items");
    }

    @Test
    public void recipesHasItsColumns() throws JSONException {
        // servings is nullable; steps is one TEXT column holding a JSON array
        assertColumns("recipes", columns(
                "id", "INTEGER NOT NULL",
                "name", "TEXT NOT NULL",
                "servings", "INTEGER NULL",
                "steps", "TEXT NOT NULL"));
        assertAutoGeneratedKey("recipes");
    }

    @Test
    public void recipeIngredientsHasItsColumns() throws JSONException {
        assertColumns("recipe_ingredients", columns(
                "id", "INTEGER NOT NULL",
                "recipe_id", "INTEGER NOT NULL",
                "name", "TEXT NOT NULL",
                "quantity", "REAL NOT NULL",
                "unit", "TEXT NOT NULL"));
        assertAutoGeneratedKey("recipe_ingredients");
    }

    @Test
    public void recipeIdReferencesRecipesAndCascadesOnDelete() throws JSONException {
        JSONArray foreignKeys = entity("recipe_ingredients").getJSONArray("foreignKeys");
        assertEquals(1, foreignKeys.length());
        JSONObject key = foreignKeys.getJSONObject(0);
        assertEquals("recipes", key.getString("table"));
        assertEquals("CASCADE", key.getString("onDelete"));
        assertEquals(Collections.singletonList("recipe_id"), strings(key.getJSONArray("columns")));
        assertEquals(Collections.singletonList("id"), strings(key.getJSONArray("referencedColumns")));
        // The other two tables point at nothing
        assertEquals(0, entity("pantry_items").getJSONArray("foreignKeys").length());
        assertEquals(0, entity("recipes").getJSONArray("foreignKeys").length());
    }

    @Test
    public void recipeIdIsIndexedByName() throws JSONException {
        JSONArray indices = entity("recipe_ingredients").getJSONArray("indices");
        assertEquals(1, indices.length());
        JSONObject index = indices.getJSONObject(0);
        assertEquals("index_recipe_ingredients_recipe_id", index.getString("name"));
        assertFalse(index.getBoolean("unique"));
        assertEquals(Collections.singletonList("recipe_id"), strings(index.getJSONArray("columnNames")));
    }

    private static void assertColumns(String table, Map<String, String> expected) throws JSONException {
        JSONArray fields = entity(table).getJSONArray("fields");
        Map<String, String> actual = new LinkedHashMap<>();
        for (int i = 0; i < fields.length(); i++) {
            JSONObject field = fields.getJSONObject(i);
            actual.put(field.getString("columnName"),
                    field.getString("affinity") + (field.getBoolean("notNull") ? " NOT NULL" : " NULL"));
        }
        assertEquals("columns of " + table, expected, actual);
    }

    private static void assertAutoGeneratedKey(String table) throws JSONException {
        JSONObject primaryKey = entity(table).getJSONObject("primaryKey");
        assertTrue(table + ".id is not auto-generated", primaryKey.getBoolean("autoGenerate"));
        assertEquals(Collections.singletonList("id"), strings(primaryKey.getJSONArray("columnNames")));
    }

    private static JSONObject entity(String table) throws JSONException {
        JSONArray entities = database.getJSONArray("entities");
        for (int i = 0; i < entities.length(); i++) {
            if (entities.getJSONObject(i).getString("tableName").equals(table)) {
                return entities.getJSONObject(i);
            }
        }
        throw new AssertionError("No table " + table + " in " + SCHEMA);
    }

    private static Map<String, String> columns(String... nameThenType) {
        Map<String, String> columns = new LinkedHashMap<>();
        for (int i = 0; i < nameThenType.length; i += 2) {
            columns.put(nameThenType[i], nameThenType[i + 1]);
        }
        return columns;
    }

    private static List<String> strings(JSONArray array) throws JSONException {
        List<String> strings = new ArrayList<>();
        for (int i = 0; i < array.length(); i++) {
            strings.add(array.getString(i));
        }
        return strings;
    }
}
