package com.btk.spm.data.model;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

import com.btk.spm.domain.Unit;

import java.time.LocalDate;
import java.util.Objects;

/**
 * One ingredient the user has: a row of {@code pantry_items}, the table the rubric's CRUD cycle is
 * marked on (decision 7).
 *
 * <p>Room is the single source of truth for the pantry (decision 1, non-negotiable 6): screens
 * observe this table through a repository and never keep a copy of it. The {@link Unit} and the
 * expiry date reach SQLite through {@code Converters}, as {@code TEXT} and {@code INTEGER}.
 *
 * <p>Instances are immutable. An edit is a new {@code PantryItem} with the same {@link #getId() id},
 * which is what Room's {@code @Update} matches on. Nothing here validates a value (a blank name, a
 * zero quantity): {@code Validators} does that before anything is written (non-negotiable 8), and
 * the {@code NOT NULL} columns are the database's own last check.
 */
@Entity(tableName = "pantry_items")
public class PantryItem {

    /**
     * Column {@code id}: the row's primary key, generated by SQLite on insert. {@code 0} means "not
     * inserted yet", so Room generates one; inserting an item with its old id set (undo after a
     * delete, Issue 16) puts back the same row.
     */
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    private final long id;

    /**
     * Column {@code name}, {@code NOT NULL}: what the user typed, trimmed by the form. It is kept as
     * typed ("Tomatoes") for display; the matcher normalises a copy when it compares (Issue 18).
     */
    @NonNull
    @ColumnInfo(name = "name")
    private final String name;

    /**
     * Column {@code quantity}, {@code NOT NULL} (a primitive): how much there is, in {@link #unit}.
     * A {@code double}, because pantries hold 0.5 kg as often as 3 eggs; the form keeps it above 0.
     */
    @ColumnInfo(name = "quantity")
    private final double quantity;

    /**
     * Column {@code unit}, {@code TEXT NOT NULL} holding the enum constant's name ({@code "KG"}), never
     * its display symbol or ordinal (non-negotiable 7). Its {@code UnitKind} decides what it can be
     * compared with (decision 5).
     */
    @NonNull
    @ColumnInfo(name = "unit")
    private final Unit unit;

    /**
     * Column {@code expiry_date}, a nullable {@code INTEGER} epoch day, so SQLite sorts by it as a
     * number. {@code null} means the item never expires (decision 6), which is why the column is
     * nullable rather than using a far-future date. {@code java.time} needs no desugaring at
     * {@code minSdk 26} (decision 4).
     */
    @Nullable
    @ColumnInfo(name = "expiry_date")
    private final LocalDate expiryDate;

    /**
     * Column {@code created_at}, {@code NOT NULL}: when the item was first added, in epoch
     * milliseconds. A stable second sort key, so two items with the same name or expiry keep their
     * order between refreshes. An edit keeps the original value.
     */
    @ColumnInfo(name = "created_at")
    private final long createdAt;

    /**
     * Creates an item with every column given, as Room does when it reads a row, and as an edit does
     * when it keeps the row's {@code id} and {@code createdAt}.
     *
     * @param id the primary key, or {@code 0} for an item not inserted yet
     * @param name the ingredient's name as the user typed it
     * @param quantity how much there is, in {@code unit}
     * @param unit the unit {@code quantity} is measured in
     * @param expiryDate the last day it is good, or {@code null} if it never expires
     * @param createdAt when it was first added, in epoch milliseconds
     */
    public PantryItem(long id, @NonNull String name, double quantity, @NonNull Unit unit,
                      @Nullable LocalDate expiryDate, long createdAt) {
        this.id = id;
        this.name = name;
        this.quantity = quantity;
        this.unit = unit;
        this.expiryDate = expiryDate;
        this.createdAt = createdAt;
    }

    /**
     * Creates an item that has not been inserted yet: its id is {@code 0}, so the database assigns
     * one. The caller passes the creation time so tests can fix it.
     *
     * @param name the ingredient's name as the user typed it
     * @param quantity how much there is, in {@code unit}
     * @param unit the unit {@code quantity} is measured in
     * @param expiryDate the last day it is good, or {@code null} if it never expires
     * @param createdAt the time it is being added, in epoch milliseconds
     */
    @Ignore
    public PantryItem(@NonNull String name, double quantity, @NonNull Unit unit,
                      @Nullable LocalDate expiryDate, long createdAt) {
        this(0L, name, quantity, unit, expiryDate, createdAt);
    }

    /**
     * Returns the primary key.
     *
     * @return the row id, or {@code 0} if this item has not been inserted
     */
    public long getId() {
        return id;
    }

    /**
     * Returns the name as the user typed it.
     *
     * @return the name, never {@code null} for a stored row
     */
    @NonNull
    public String getName() {
        return name;
    }

    /**
     * Returns how much of the ingredient there is, in {@link #getUnit()}.
     *
     * @return the quantity
     */
    public double getQuantity() {
        return quantity;
    }

    /**
     * Returns the unit the quantity is measured in.
     *
     * @return the unit, never {@code null} for a stored row
     */
    @NonNull
    public Unit getUnit() {
        return unit;
    }

    /**
     * Returns the last day the item is good.
     *
     * @return the expiry date, or {@code null} if it never expires (decision 6)
     */
    @Nullable
    public LocalDate getExpiryDate() {
        return expiryDate;
    }

    /**
     * Returns when the item was first added.
     *
     * @return epoch milliseconds
     */
    public long getCreatedAt() {
        return createdAt;
    }

    /**
     * Two items are equal when every column is equal, the id included, so a list adapter's
     * {@code DiffUtil} can tell an edited row from an unchanged one and a test can compare what it
     * wrote with what it read back.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof PantryItem)) {
            return false;
        }
        PantryItem other = (PantryItem) o;
        return id == other.id
                && Double.compare(quantity, other.quantity) == 0
                && createdAt == other.createdAt
                && Objects.equals(name, other.name)
                && unit == other.unit
                && Objects.equals(expiryDate, other.expiryDate);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, quantity, unit, expiryDate, createdAt);
    }

    /** Returns a one-line form for test failures and debug logs, such as {@code PantryItem{3, egg, 6.0 pcs, null}}. */
    @NonNull
    @Override
    public String toString() {
        return "PantryItem{" + id + ", " + name + ", " + quantity + " " + unit + ", " + expiryDate + "}";
    }
}
