package com.btk.spm.data.model;

import androidx.annotation.NonNull;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.Ignore;
import androidx.room.Index;
import androidx.room.PrimaryKey;

import com.btk.spm.domain.Unit;

import java.util.Objects;

/**
 * One ingredient a recipe needs, in a quantity: a row of {@code recipe_ingredients}. A recipe with
 * five ingredients has five rows, each pointing at it through {@link #getRecipeId() recipe_id}.
 *
 * <p>{@code recipe_id} is a foreign key to {@code recipes.id} with {@code ON DELETE CASCADE}, so a
 * deleted recipe takes its ingredients with it and no row can point at a recipe that does not exist
 * (decision 1 chose Room partly for checks like this). It has an index, because every read of a
 * recipe's ingredients filters on it and SQLite does not index a foreign key column by itself.
 *
 * <p>These rows are seed data, read-only like their recipe (decision 7). Instances are immutable;
 * {@link #withRecipeId(long)} gives the copy that is inserted once the parent's id is known.
 */
@Entity(
        tableName = "recipe_ingredients",
        foreignKeys = @ForeignKey(
                entity = Recipe.class,
                parentColumns = "id",
                childColumns = "recipe_id",
                onDelete = ForeignKey.CASCADE),
        indices = @Index("recipe_id"))
public class RecipeIngredient {

    /** Column {@code id}: the row's primary key, generated by SQLite on insert; {@code 0} until then. */
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    private final long id;

    /**
     * Column {@code recipe_id}, {@code NOT NULL}: the {@code recipes.id} this ingredient belongs to.
     * Foreign key with {@code ON DELETE CASCADE}, indexed as {@code index_recipe_ingredients_recipe_id}.
     */
    @ColumnInfo(name = "recipe_id")
    private final long recipeId;

    /**
     * Column {@code name}, {@code NOT NULL}: the ingredient in its canonical form, trimmed, lower case
     * and singular ("tomato", "spring onion"), as the seed writes it (Issue 11). The matcher compares
     * it with a normalised pantry name (Issue 18); this table does not enforce the form, the seed's
     * tests do.
     */
    @NonNull
    @ColumnInfo(name = "name")
    private final String name;

    /**
     * Column {@code quantity}, {@code NOT NULL} (a primitive): how much the recipe needs, in
     * {@link #unit}. The strict rule (brief 2.3) asks the pantry for at least this much.
     */
    @ColumnInfo(name = "quantity")
    private final double quantity;

    /**
     * Column {@code unit}, {@code TEXT NOT NULL} holding the enum constant's name ({@code "TBSP"}),
     * never its symbol or ordinal (non-negotiable 7). The seed picks the kind a pantry would use for
     * the ingredient, because a mass never matches a volume (decision 5).
     */
    @NonNull
    @ColumnInfo(name = "unit")
    private final Unit unit;

    /**
     * Creates an ingredient with every column given, as Room does when it reads a row.
     *
     * @param id the primary key, or {@code 0} for a row not inserted yet
     * @param recipeId the id of the recipe that needs it
     * @param name the canonical ingredient name
     * @param quantity how much the recipe needs, in {@code unit}
     * @param unit the unit {@code quantity} is measured in
     */
    public RecipeIngredient(long id, long recipeId, @NonNull String name, double quantity, @NonNull Unit unit) {
        this.id = id;
        this.recipeId = recipeId;
        this.name = name;
        this.quantity = quantity;
        this.unit = unit;
    }

    /**
     * Creates an ingredient that has not been inserted yet and whose recipe may not have an id yet;
     * both ids are {@code 0} until {@link #withRecipeId(long)} sets the parent's.
     *
     * @param name the canonical ingredient name
     * @param quantity how much the recipe needs, in {@code unit}
     * @param unit the unit {@code quantity} is measured in
     */
    @Ignore
    public RecipeIngredient(@NonNull String name, double quantity, @NonNull Unit unit) {
        this(0L, 0L, name, quantity, unit);
    }

    /**
     * Returns a copy of this ingredient that belongs to the recipe with id {@code recipeId}, for
     * inserting the ingredients after their recipe in one transaction (Issue 10).
     *
     * @param recipeId the parent recipe's generated id
     * @return a new ingredient, identical but for {@code recipe_id}
     */
    @NonNull
    public RecipeIngredient withRecipeId(long recipeId) {
        return new RecipeIngredient(id, recipeId, name, quantity, unit);
    }

    /**
     * Returns the primary key.
     *
     * @return the row id, or {@code 0} if this ingredient has not been inserted
     */
    public long getId() {
        return id;
    }

    /**
     * Returns the id of the recipe that needs this ingredient.
     *
     * @return the parent's {@code recipes.id}, or {@code 0} before {@link #withRecipeId(long)}
     */
    public long getRecipeId() {
        return recipeId;
    }

    /**
     * Returns the canonical ingredient name.
     *
     * @return the name, never {@code null} for a stored row
     */
    @NonNull
    public String getName() {
        return name;
    }

    /**
     * Returns how much the recipe needs, in {@link #getUnit()}.
     *
     * @return the quantity
     */
    public double getQuantity() {
        return quantity;
    }

    /**
     * Returns the unit the quantity is measured in.
     *
     * @return the unit, never {@code null} for a stored row
     */
    @NonNull
    public Unit getUnit() {
        return unit;
    }

    /** Two ingredients are equal when every column is equal, both ids included. */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof RecipeIngredient)) {
            return false;
        }
        RecipeIngredient other = (RecipeIngredient) o;
        return id == other.id
                && recipeId == other.recipeId
                && Double.compare(quantity, other.quantity) == 0
                && Objects.equals(name, other.name)
                && unit == other.unit;
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, recipeId, name, quantity, unit);
    }

    /** Returns a one-line form for test failures and debug logs, such as {@code RecipeIngredient{9, recipe 4, egg, 2.0 pcs}}. */
    @NonNull
    @Override
    public String toString() {
        return "RecipeIngredient{" + id + ", recipe " + recipeId + ", " + name + ", " + quantity + " " + unit + "}";
    }
}
