package com.btk.spm.data.model;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

/**
 * A recipe that can be cooked: a row of {@code recipes}. Its required ingredients are rows of
 * {@code recipe_ingredients} pointing back at it ({@link RecipeIngredient}); read the two together
 * through {@link RecipeWithIngredients}.
 *
 * <p>Recipes are read-only seed data (decision 7): the twenty of them are inserted once on first run
 * (Issue 11) and never edited, so this table carries no {@code updated_at} and no user flags such as
 * a favourite. Room over SQLite on the device holds them next to the pantry (decision 1), so matching
 * needs no network.
 *
 * <p>Instances are immutable and the steps list cannot be changed after construction.
 */
@Entity(tableName = "recipes")
public class Recipe {

    /** Column {@code id}: the row's primary key, generated by SQLite on insert; {@code 0} until then. */
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    private final long id;

    /**
     * Column {@code name}, {@code NOT NULL}: the recipe's title as the list and the detail screen show
     * it, such as "Cheese omelette". Unique across the seed (Issue 11 tests it).
     */
    @NonNull
    @ColumnInfo(name = "name")
    private final String name;

    /**
     * Column {@code servings}, a nullable {@code INTEGER}: how many people the recipe feeds. The brief
     * does not ask for it, so a recipe may leave it out; a boxed {@code null} says "not given" where a
     * {@code 0} would be a magic number the screens would have to know about.
     */
    @Nullable
    @ColumnInfo(name = "servings")
    private final Integer servings;

    /**
     * Column {@code steps}, {@code TEXT NOT NULL}: the method, one string per step, stored as one JSON
     * array by {@code Converters} (decided in Issue 8). A newline-joined string would break the day a
     * step contains a line break, and a {@code recipe_steps} table would add a relation nothing needs.
     * The detail screen numbers the steps when it shows them (Issue 25), so they are stored unnumbered.
     */
    @NonNull
    @ColumnInfo(name = "steps")
    private final List<String> steps;

    /**
     * Creates a recipe with every column given, as Room does when it reads a row.
     *
     * @param id the primary key, or {@code 0} for a recipe not inserted yet
     * @param name the recipe's title
     * @param servings how many it feeds, or {@code null} if not given
     * @param steps the method in order; copied, so later changes to the caller's list do not reach it
     * @throws NullPointerException if {@code steps} is {@code null}
     */
    public Recipe(long id, @NonNull String name, @Nullable Integer servings, @NonNull List<String> steps) {
        this.id = id;
        this.name = name;
        this.servings = servings;
        this.steps = Collections.unmodifiableList(new ArrayList<>(Objects.requireNonNull(steps, "steps")));
    }

    /**
     * Creates a recipe that has not been inserted yet, as the seeder does: its id is {@code 0}, so the
     * database assigns one.
     *
     * @param name the recipe's title
     * @param servings how many it feeds, or {@code null} if not given
     * @param steps the method in order; copied
     * @throws NullPointerException if {@code steps} is {@code null}
     */
    @Ignore
    public Recipe(@NonNull String name, @Nullable Integer servings, @NonNull List<String> steps) {
        this(0L, name, servings, steps);
    }

    /**
     * Returns the primary key.
     *
     * @return the row id, or {@code 0} if this recipe has not been inserted
     */
    public long getId() {
        return id;
    }

    /**
     * Returns the recipe's title.
     *
     * @return the name, never {@code null} for a stored row
     */
    @NonNull
    public String getName() {
        return name;
    }

    /**
     * Returns how many people the recipe feeds.
     *
     * @return the servings, or {@code null} if the recipe does not say
     */
    @Nullable
    public Integer getServings() {
        return servings;
    }

    /**
     * Returns the method, one string per step, in order.
     *
     * @return an unmodifiable list, never {@code null}
     */
    @NonNull
    public List<String> getSteps() {
        return steps;
    }

    /** Two recipes are equal when every column is equal, the id and the order of the steps included. */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Recipe)) {
            return false;
        }
        Recipe other = (Recipe) o;
        return id == other.id
                && Objects.equals(name, other.name)
                && Objects.equals(servings, other.servings)
                && steps.equals(other.steps);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, servings, steps);
    }

    /** Returns a one-line form for test failures and debug logs, such as {@code Recipe{4, Cheese omelette, 3 steps}}. */
    @NonNull
    @Override
    public String toString() {
        return "Recipe{" + id + ", " + name + ", " + steps.size() + " steps}";
    }
}
